In [1]:
import pandas as pd

borrower_df = pd.read_csv('data/Borrower.csv')
loan_df = pd.read_csv('data/Loan.csv')

In [2]:
loan_feature = loan_df[['loanId', 'memberId', 'date', 'purpose', 'isJointApplication',\
                   'loanAmount', 'term', 'interestRate', 'monthlyPayment', 'grade', 'loanStatus']]
loan_feature.set_index('loanId')
loan_feature

,loanId,memberId,date,purpose,isJointApplication,loanAmount,term,interestRate,monthlyPayment,grade,loanStatus
0,1888978,2305095,12/10/2014,debtconsolidation,0.0,25190.0,60 months,6.25,490,E3,Current
1,1299695,2610493,9/15/2014,debtconsolidation,0.0,21189.0,60 months,10.49,455,B3,Current
2,1875016,2491679,9/11/2014,debtconsolidation,0.0,29908.0,60 months,9.11,622,B2,Current
3,1440478,2092798,4/22/2016,homeimprovement,0.0,13053.0,48 months,11.89,343,B3,Current
4,1124634,2633077,2/3/2016,debtconsolidation,0.0,24613.0,60 months,15.13,587,A3,Current
5,1697652,2385245,11/14/2015,debtconsolidation,0.0,17905.0,60 months,10.43,384,A1,Current
6,1050350,2796457,5/14/2014,debtconsolidation,0.0,26238.0,36 months,10.96,859,B3,Current
7,1278582,2822245,4/8/2015,healthcare,0.0,21940.0,48 months,10.28,559,B1,Current
8,1245174,2462353,10/22/2014,debtconsolidation,0.0,18195.0,36 months,12.08,605,A1,Current
9,1127834,2404666,12/12/2015,debtconsolidation,0.0,24418.0,48 months,11.63,639,B1,Current
10,1155124,2211682,8/15/2014,debtconsolidation,0.0,25612.0,36 months,17.99,926,B2,Current
11,1299358,2306064,2/4/2016,debtconsolidation,0.0,25659.0,48 months,14.36,706,C1,Current
12,1366944,2727099,11/13/2015,debtconsolidation,0.0,17914.0,60 months,13.28,410,B1,Current
13,1183120,2248818,12/1/2015,debtconsolidation,0.0,15555.0,36 months,13.02,524,A2,Current
14,1702217,2276470,5/14/2014,debtconsolidation,0.0,20447.0,36 months,13.35,692,D2,Current
15,1541157,2437396,11/22/2015,debtconsolidation,0.0,31487.0,48 months,11.70,825,A2,Current
16,1673267,2537040,5/5/2016,debtconsolidation,0.0,21991.0,60 months,9.72,464,C1,Current
17,1667717,2264122,5/22/2015,debtconsolidation,0.0,18067.0,48 months,15.30,506,A3,Current
18,1579131,2723224,3/30/2016,debtconsolidation,1.0,24085.0,60 months,13.74,557,B2,Current
19,1769263,2294710,8/31/2014,debtconsolidation,0.0,21298.0,60 months,6.94,421,C1,Current
20,1329565,2273732,5/1/2015,homeimprovement,0.0,27036.0,48 months,12.72,722,A3,Current
21,1303036,2841525,11/5/2015,homeimprovement,0.0,18883.0,48 months,9.76,477,C2,Current
22,1715374,2688887,10/20/2014,debtconsolidation,0.0,23140.0,36 months,14.89,801,E2,Current
23,1514131,2767856,5/12/2016,debtconsolidation,0.0,16569.0,36 months,7.15,513,E1,Current
24,1892304,2526733,5/15/2016,education,0.0,24686.0,60 months,6.39,482,A3,Current
25,1632177,2455559,2/8/2016,debtconsolidation,1.0,16905.0,36 months,10.16,547,D1,Current
26,1280412,2113837,3/28/2016,debtconsolidation,0.0,14369.0,36 months,11.61,475,D1,Current
27,1327382,2093340,8/7/2015,debtconsolidation,0.0,17045.0,60 months,7.67,343,B1,Current
28,1062053,2094750,6/22/2016,debtconsolidation,0.0,16621.0,36 months,13.65,565,C1,Current
29,1596972,2787329,6/24/2014,debtconsolidation,0.0,20006.0,60 months,11.25,437,A3,Current
...,...,...,...,...,...,...,...,...,...,...,...
99970,1260979,2193116,8/17/2014,debtconsolidation,0.0,18862.0,48 months,12.94,505,B1,Current
99971,1109257,2622481,11/3/2015,debtconsolidation,0.0,22108.0,60 months,15.52,532,B3,Current
99972,1624342,2357237,5/28/2016,debtconsolidation,0.0,18793.0,48 months,22.81,600,C3,Default
99973,1304043,2856300,9/18/2015,business,0.0,21503.0,36 months,4.53,640,C3,Default
99974,1857973,2221641,5/12/2015,healthcare,0.0,17259.0,48 months,7.84,420,C2,Current
99975,1444550,2756502,2/5/2015,debtconsolidation,0.0,24600.0,36 months,5.22,740,A1,Current
99976,1587993,2400602,2/23/2015,debtconsolidation,0.0,19081.0,48 months,13.55,517,C3,Current
99977,1856627,2110767,12/26/2015,debtconsolidation,0.0,21579.0,60 months,13.30,494,E2,Default
99978,1111871,2152759,6/26/2015,debtconsolidation,0.0,12977.0,36 months,11.86,430,C1,Current
99979,1269638,2689986,11/6/2014,debtconsolidation,0.0,13650.0,60 months,8.79,282,B2,Current
99980,1781148,2325786,6/17/2016,debtconsolidation,0.0,22747.0,48 months,10.04,577,B3,Current
99981,1775463,2533299,10/29/2014,debtconsolidation,0.0,15800.0,48 months,5.26,366,B3,Current
99982,1137731,2501378,3/9/2015,debtconsolidation,0.0,23154.0,48 months,13.35,625,B3,Current
99983,1376371,2598513,6/21/2015,debtconsolidation,0.0,23619.0,48 months,12.88,632,D2,Current
99984,1173872,2278876,7/28/2015,debtconsolidation,0.0,22910.0,48 months,16.23,652,B2,Current
99985,1860757,2727504,9/6/2015,debtconsolidation,0.0,24392.0,36 months,12.54,816,A2,Current
99986,1788496,2326679,12/11/2014,debtconsolidation,0.0,24184.0,60 months,13.11,552,A1,Current
99987,1180267,2629077,1/25/2015,debtconsolidation,0.0,20657.0,36 months,15.18,718,A1,Current
99988,1834750,2820536,12/29/2014,debtconsolidation,0.0,19643.0,36 months,13.79,669,A2,Current
99989,1608222,2706114,11/28/2015,debtconsolidation,0.0,17946.0,36 months,8.94,570,B1,Current
99990,1703351,2885693,1/10/2016,debtconsolidation,0.0,23145.0,60 months,18.34,592,B2,Current
99991,1895440,2701983,2/20/2016,debtconsolidation,0.0,21878.0,48 months,19.60,661,D2,Current
99992,1546986,2231561,3/22/2016,debtconsolidation,0.0,17102.0,36 months,14.65,590,E3,Current
99993,1220873,2475792,3/1/2016,debtconsolidation,0.0,28289.0,36 months,10.22,916,B2,Current
99994,1792576,2012965,7/26/2015,debtconsolidation,0.0,15318.0,60 months,14.01,357,A1,Current
99995,1208167,2069462,5/25/2016,debtconsolidation,0.0,25874.0,60 months,10.95,562,A2,Current
99996,1097349,2218175,6/5/2015,debtconsolidation,0.0,18557.0,60 months,5.31,353,A1,Current
99997,1873914,2262127,11/13/2014,debtconsolidation,0.0,15877.0,36 months,9.87,511,A2,Current
99998,1572282,2501174,6/6/2015,debtconsolidation,0.0,15601.0,60 months,7.31,311,C3,Current
99999,1877390,2134068,8/10/2015,other,0.0,20500.0,48 months,12.98,550,A2,Current

In [3]:
borrower_feature = borrower_df[['memberId', 'residentialState', 'yearsEmployment',\
                                'homeOwnership', 'annualIncome', 'incomeVerified',\
                                'dtiRatio', 'lengthCreditHistory', 'numTotalCreditLines',\
                                'numOpenCreditLines', 'numOpenCreditLines1Year',\
                                'revolvingBalance', 'revolvingUtilizationRate',\
                                'numDerogatoryRec', 'numDelinquency2Years',\
                                'numChargeoff1year', 'numInquiries6Mon']]
borrower_feature.set_index('memberId')
borrower_feature

,memberId,residentialState,yearsEmployment,homeOwnership,annualIncome,incomeVerified,dtiRatio,lengthCreditHistory,numTotalCreditLines,numOpenCreditLines,numOpenCreditLines1Year,revolvingBalance,revolvingUtilizationRate,numDerogatoryRec,numDelinquency2Years,numChargeoff1year,numInquiries6Mon
0,2305095,NM,10+ years,rent,56471,1,16.80,6,11,9.0,6,14301,49.02,0,19,10,0
1,2610493,WA,2-5 years,rent,55038,0,19.99,22,8,7.0,4,18262,72.40,1,0,0,0
2,2491679,MS,< 1 year,rent,56610,1,14.33,5,8,5.0,5,10799,66.27,0,1,1,0
3,2092798,TX,6-9 years,own,54887,1,14.80,12,14,7.0,3,15272,61.05,1,0,0,3
4,2633077,MA,2-5 years,rent,53522,1,10.14,4,21,19.0,10,19316,56.39,2,14,7,1
5,2385245,NH,2-5 years,rent,58459,0,15.77,1,18,15.0,8,18830,59.61,0,0,0,0
6,2796457,VT,6-9 years,rent,56611,0,13.52,1,9,7.0,5,17157,43.01,0,0,0,0
7,2822245,CA,10+ years,mortgage,58163,0,25.22,6,14,9.0,5,15867,62.55,0,0,0,0
8,2462353,IN,10+ years,rent,55636,1,9.97,10,19,12.0,5,12908,67.67,0,20,15,1
9,2404666,IL,6-9 years,mortgage,54599,0,20.90,26,16,11.0,10,15235,58.07,1,0,0,1
10,2211682,IA,1 year,own,56781,1,8.62,4,15,14.0,11,15900,37.70,0,0,0,10
11,2306064,UT,6-9 years,mortgage,51089,1,17.54,7,21,15.0,8,17402,88.24,0,7,5,13
12,2727099,CA,< 1 year,rent,49704,0,15.67,5,10,9.0,7,13026,68.96,0,0,0,1
13,2248818,CT,10+ years,mortgage,56864,0,9.26,7,13,12.0,7,11140,71.85,0,5,5,2
14,2276470,ID,10+ years,mortgage,56075,1,13.11,14,14,12.0,9,10098,71.71,0,1,1,0
15,2437396,FL,1 year,rent,57647,1,21.80,3,9,7.0,6,13754,50.61,0,0,0,0
16,2537040,TN,1 year,mortgage,57635,1,8.13,8,15,8.0,7,17414,54.31,0,0,0,1
17,2264122,NV,2-5 years,own,57898,0,13.73,5,14,12.0,4,15241,53.64,0,20,11,0
18,2723224,WI,6-9 years,own,51667,1,7.89,4,25,25.0,19,14639,42.14,0,0,0,2
19,2294710,DE,6-9 years,mortgage,52092,1,21.90,4,19,11.0,6,12296,50.46,0,0,0,1
20,2273732,OR,1 year,mortgage,56815,1,20.38,13,14,9.0,4,15763,45.89,0,0,0,1
21,2841525,WY,< 1 year,mortgage,50693,0,18.00,4,2,2.0,2,11729,69.10,0,0,0,0
22,2688887,CA,6-9 years,rent,55230,1,13.89,10,15,10.0,4,10630,48.11,0,0,0,0
23,2767856,MN,< 1 year,own,60827,0,20.85,5,13,7.0,5,13469,26.70,0,0,0,2
24,2526733,FL,6-9 years,rent,59391,1,22.04,29,16,NaN,7,20634,86.97,0,0,0,1
25,2455559,IL,< 1 year,own,59310,1,23.16,9,17,13.0,11,18467,53.47,0,0,0,0
26,2113837,KY,1 year,rent,52467,1,23.29,7,16,9.0,8,14767,44.55,0,0,0,0
27,2093340,CO,6-9 years,own,55743,1,16.32,7,17,10.0,6,15808,56.17,0,1,1,0
28,2094750,CA,< 1 year,mortgage,53344,1,18.23,2,9,7.0,6,18223,59.89,10,0,0,0
29,2787329,CA,2-5 years,mortgage,51664,1,4.15,4,8,7.0,5,14902,82.14,0,6,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,2193116,WA,6-9 years,rent,58870,1,15.09,9,12,NaN,10,16425,76.77,2,0,0,1
99971,2622481,NJ,2-5 years,mortgage,49651,1,17.37,10,14,12.0,8,14548,63.35,0,0,0,1
99972,2357237,AZ,6-9 years,rent,46642,1,21.03,33,17,16.0,14,9898,58.89,0,0,0,2
99973,2856300,OR,< 1 year,own,49594,1,12.20,19,10,5.0,4,7786,41.41,0,2,1,0
99974,2221641,LA,6-9 years,mortgage,57131,1,8.19,35,12,8.0,7,13751,30.14,0,3,2,8
99975,2756502,UT,< 1 year,own,57768,1,16.04,8,15,11.0,10,14847,60.45,8,0,0,0
99976,2400602,MA,2-5 years,own,58088,1,28.59,5,16,NaN,9,15452,37.86,1,0,0,0
99977,2110767,IA,2-5 years,own,52582,0,21.54,20,18,17.0,14,13074,95.55,1,1,1,2
99978,2152759,MA,< 1 year,rent,51597,1,11.01,24,10,5.0,3,15863,40.30,0,15,8,1
99979,2689986,MN,10+ years,own,54534,0,15.25,16,17,13.0,7,15405,62.94,0,0,0,2
99980,2325786,LA,10+ years,own,58174,1,18.06,23,11,10.0,8,14013,100.00,0,0,0,1
99981,2533299,NV,< 1 year,own,53778,1,8.22,2,14,8.0,8,16686,82.90,0,3,3,1
99982,2501378,MS,2-5 years,own,54719,1,22.62,39,10,10.0,5,15956,47.81,6,0,0,10
99983,2598513,CA,2-5 years,mortgage,53782,1,23.04,22,24,24.0,24,16154,61.36,1,0,0,0
99984,2278876,FL,< 1 year,mortgage,51671,1,15.90,3,8,5.0,5,22797,78.03,0,0,0,0
99985,2727504,NJ,10+ years,rent,53627,1,15.52,3,18,10.0,4,12510,57.00,0,1,1,0
99986,2326679,AL,< 1 year,own,56478,1,18.95,1,11,9.0,6,16249,62.68,7,0,0,0
99987,2629077,IN,1 year,own,53180,1,19.61,8,14,8.0,7,13594,64.78,0,0,0,0
99988,2820536,NM,< 1 year,rent,53634,1,23.43,3,12,11.0,4,9314,43.45,2,1,1,0
99989,2706114,DC,10+ years,rent,56974,0,16.22,25,16,13.0,8,18101,72.23,0,1,1,0
99990,2885693,KY,< 1 year,own,50898,1,15.76,2,16,12.0,5,12062,77.26,1,0,0,0
99991,2701983,CA,< 1 year,mortgage,58452,0,13.88,10,16,15.0,10,16315,45.37,0,0,0,1
99992,2231561,NY,10+ years,mortgage,58632,1,28.01,5,11,11.0,6,15726,65.93,3,8,4,1
99993,2475792,CA,6-9 years,rent,57052,1,21.03,6,12,12.0,6,15915,70.22,0,0,0,0
99994,2012965,IA,1 year,rent,56664,1,12.27,9,12,11.0,9,15069,54.07,0,3,2,7
99995,2069462,LA,2-5 years,own,58987,0,21.62,2,16,10.0,8,15113,77.01,0,6,5,18
99996,2218175,MO,6-9 years,rent,54245,1,15.60,11,11,7.0,4,13504,80.18,0,0,0,1
99997,2262127,DE,1 year,rent,54923,0,13.96,2,21,13.0,10,18108,77.28,0,0,0,1
99998,2501174,CA,1 year,own,57809,1,9.07,36,18,12.0,4,17918,61.01,10,0,0,1
99999,2134068,MN,6-9 years,rent,52150,1,11.35,6,13,13.0,5,17487,89.47,0,0,0,1

In [4]:
merged_df = pd.merge(loan_feature, borrower_feature, on='memberId')
merged_df.sort_values(['memberId', 'loanId'], ascending=True)

,loanId,memberId,date,purpose,isJointApplication,loanAmount,term,interestRate,monthlyPayment,grade,...,lengthCreditHistory,numTotalCreditLines,numOpenCreditLines,numOpenCreditLines1Year,revolvingBalance,revolvingUtilizationRate,numDerogatoryRec,numDelinquency2Years,numChargeoff1year,numInquiries6Mon
81962,1399936,2000006,12/23/2015,debtconsolidation,0.0,17872.0,36 months,6.55,548,A1,...,27,22,14.0,14,19227,31.81,0,0,0,1
56536,1836125,2000012,7/9/2015,education,0.0,13822.0,60 months,13.35,317,A2,...,3,14,13.0,11,17571,77.58,2,0,0,0
41727,1641734,2000017,1/9/2016,debtconsolidation,0.0,12872.0,48 months,14.25,353,A2,...,4,13,7.0,3,11688,49.81,0,0,0,0
85254,1610317,2000025,10/8/2015,debtconsolidation,0.0,13572.0,48 months,10.06,345,C2,...,8,15,NaN,7,12401,69.93,5,0,0,0
13110,1125395,2000030,8/4/2014,debtconsolidation,0.0,NaN,36 months,11.73,627,C1,...,6,15,9.0,8,16792,44.64,0,0,0,0
48726,1770506,2000041,5/17/2015,debtconsolidation,0.0,16433.0,48 months,10.11,418,E3,...,2,18,13.0,11,13621,60.28,0,0,0,1
44185,1758975,2000063,12/26/2014,debtconsolidation,0.0,22158.0,60 months,8.08,450,B3,...,6,11,6.0,6,15436,68.88,0,0,0,0
85458,1169074,2000064,6/22/2016,debtconsolidation,0.0,13003.0,36 months,9.64,417,A1,...,4,18,18.0,18,16122,72.51,0,0,0,0
93456,1391820,2000066,12/16/2015,debtconsolidation,0.0,24044.0,60 months,6.28,468,A2,...,9,20,15.0,14,14503,63.09,0,0,0,0
41863,1595785,2000069,8/3/2015,debtconsolidation,0.0,19139.0,NaN,9.80,484,D3,...,36,14,8.0,6,17700,75.49,0,0,0,1
73934,1683127,2000073,9/16/2014,debtconsolidation,0.0,20017.0,48 months,11.43,522,E2,...,37,21,16.0,12,12000,63.20,0,9,6,0
17956,1436023,2000083,6/14/2016,debtconsolidation,0.0,29158.0,48 months,6.76,695,B2,...,26,13,10.0,9,8376,42.39,0,0,0,0
73494,1140328,2000099,4/5/2015,debtconsolidation,0.0,10444.0,48 months,7.37,252,A2,...,35,17,11.0,5,17009,42.33,0,0,0,0
40851,1744489,2000110,1/27/2016,debtconsolidation,0.0,21508.0,36 months,4.94,644,A1,...,29,6,4.0,4,14212,59.18,0,0,0,1
8218,1339415,2000129,3/1/2015,debtconsolidation,1.0,24646.0,48 months,10.47,631,A3,...,30,18,12.0,11,16842,67.96,3,1,1,1
50869,1377566,2000131,4/8/2015,debtconsolidation,0.0,11567.0,36 months,14.01,395,C1,...,10,21,17.0,17,12419,55.77,0,0,0,0
98828,1708051,2000132,11/1/2014,debtconsolidation,0.0,15873.0,48 months,5.07,366,A3,...,31,25,15.0,14,16468,65.07,0,0,0,1
60037,1343798,2000152,10/23/2014,debtconsolidation,0.0,30234.0,60 months,9.85,640,A3,...,7,18,15.0,9,16694,74.13,0,0,0,0
70352,1080532,2000156,12/29/2014,debtconsolidation,0.0,27189.0,48 months,11.16,705,B3,...,9,13,11.0,5,17884,33.45,2,0,0,0
40200,1321900,2000159,8/16/2014,debtconsolidation,0.0,16600.0,48 months,5.71,388,B1,...,13,16,9.0,8,13343,99.52,0,0,0,2
13794,1250755,2000160,9/24/2015,debtconsolidation,0.0,20747.0,36 months,8.79,658,A1,...,23,14,12.0,10,15283,52.57,0,0,0,1
32563,1566109,2000166,6/13/2014,other,0.0,23237.0,60 months,13.62,536,E1,...,6,19,14.0,8,12093,50.47,0,0,0,0
66819,1572664,2000185,5/30/2016,debtconsolidation,0.0,20199.0,60 months,6.85,399,C2,...,6,14,14.0,13,17890,56.13,1,0,0,1
48140,1748662,2000187,10/17/2015,debtconsolidation,0.0,16047.0,36 months,15.04,557,C1,...,7,10,8.0,6,16104,95.14,11,5,4,0
68538,1468971,2000203,4/30/2015,debtconsolidation,0.0,25806.0,60 months,8.01,523,C2,...,3,7,6.0,3,14355,68.65,0,0,0,1
28221,1068316,2000207,1/20/2015,debtconsolidation,0.0,20045.0,36 months,12.95,675,A3,...,14,15,10.0,9,14774,55.34,0,0,0,3
93773,1057886,2000210,4/27/2016,debtconsolidation,0.0,15166.0,36 months,10.25,491,C1,...,5,15,10.0,8,15556,87.75,0,0,0,0
90510,1757145,2000222,11/21/2015,debtconsolidation,0.0,17109.0,36 months,8.08,537,A1,...,6,12,8.0,4,14031,63.32,0,0,0,0
7134,1278931,2000225,6/2/2014,debtconsolidation,0.0,19033.0,36 months,8.57,601,A2,...,6,16,13.0,6,16968,47.41,0,0,0,4
39526,1017887,2000235,9/12/2015,debtconsolidation,0.0,18394.0,36 months,8.80,583,C1,...,9,16,13.0,10,12385,23.36,0,12,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81871,1516017,2899787,8/29/2015,debtconsolidation,0.0,23807.0,60 months,8.40,487,B2,...,40,24,21.0,14,15091,97.47,0,0,0,0
51833,1440477,2899797,12/3/2014,business,0.0,24914.0,48 months,6.07,586,C1,...,6,18,16.0,14,13976,78.13,0,0,0,0
4414,1334744,2899799,1/26/2016,debtconsolidation,0.0,28201.0,60 months,6.62,553,B3,...,5,12,7.0,4,14095,71.37,0,0,0,2
85656,1428104,2899801,5/25/2016,debtconsolidation,0.0,20833.0,48 months,16.60,597,B2,...,4,10,6.0,4,13769,94.99,0,0,0,1
28419,1722964,2899802,6/22/2015,debtconsolidation,0.0,20554.0,60 months,14.08,479,C1,...,4,12,11.0,7,13353,53.63,0,0,0,1
70485,1024595,2899816,6/2/2015,debtconsolidation,0.0,18905.0,48 months,4.53,431,C3,...,5,11,8.0,8,13438,57.45,10,3,2,0
52086,1000793,2899820,8/8/2014,business,0.0,10485.0,48 months,12.36,278,A3,...,3,10,9.0,6,18189,51.48,0,1,1,0
79656,1744608,2899831,3/26/2016,debtconsolidation,0.0,23850.0,60 months,7.91,483,B1,...,8,15,11.0,4,16132,68.47,1,0,0,17
65512,1744970,2899844,10/17/2014,debtconsolidation,0.0,16804.0,48 months,6.69,400,C1,...,40,15,8.0,3,15320,65.49,0,0,0,2
2939,1449339,2899845,4/12/2015,debtconsolidation,1.0,25069.0,48 months,20.71,772,B1,...,6,17,15.0,11,15754,59.20,0,0,0,3
627,1025234,2899855,9/1/2015,debtconsolidation,0.0,19854.0,36 months,7.24,615,B2,...,3,18,16.0,15,18691,55.65,0,0,0,0
29561,1466174,2899858,2/29/2016,healthcare,0.0,15031.0,48 months,10.38,384,A3,...,5,15,14.0,7,16090,63.87,0,0,0,0
3508,1563548,2899864,10/9/2015,debtconsolidation,0.0,19034.0,48 months,14.37,524,A1,...,31,19,11.0,10,16825,69.80,0,0,0,17
65662,1891692,2899868,6/15/2014,debtconsolidation,0.0,18680.0,48 months,10.96,482,B1,...,3,11,9.0,3,18511,71.90,9,0,0,1
2613,1419475,2899873,5/9/2015,debtconsolidation,0.0,16334.0,60 months,7.14,325,B3,...,10,11,10.0,7,12262,81.72,0,0,0,2
25558,1895231,2899879,10/3/2015,debtconsolidation,0.0,22076.0,60 months,7.46,442,B1,...,5,8,7.0,5,16366,41.08,0,0,0,0
72375,1415242,2899887,12/24/2014,debtconsolidation,0.0,14809.0,36 months,10.70,483,B3,...,6,12,12.0,10,15980,71.52,0,0,0,0
55337,1661415,2899893,12/26/2014,debtconsolidation,0.0,19298.0,36 months,5.15,580,D3,...,2,19,10.0,4,15109,50.89,0,0,0,1
93793,1349611,2899910,1/3/2016,debtconsolidation,0.0,15364.0,60 months,6.51,301,A3,...,4,18,16.0,9,12178,29.29,0,9,5,0
19404,1835774,2899924,5/5/2016,homeimprovement,0.0,21338.0,60 months,15.41,512,A3,...,3,11,8.0,5,13948,50.40,0,0,0,0
12154,1134995,2899930,8/9/2015,auto,1.0,30518.0,36 months,8.95,970,C3,...,3,7,4.0,3,15667,48.70,0,0,0,2
77532,1136392,2899934,11/18/2014,debtconsolidation,0.0,14235.0,60 months,9.06,296,A1,...,6,18,13.0,11,8936,47.00,0,0,0,2
72902,1688791,2899937,12/28/2015,other,0.0,28661.0,48 months,19.64,867,D1,...,1,13,12.0,10,16052,72.17,1,0,0,13
52708,1350760,2899953,12/21/2014,debtconsolidation,0.0,21322.0,48 months,6.95,510,B2,...,4,22,12.0,6,17313,26.99,5,0,0,1
68096,1508465,2899956,2/11/2016,homeimprovement,0.0,18913.0,48 months,8.26,464,C2,...,6,12,12.0,11,13260,70.46,6,0,0,0
15118,1355482,2899965,11/1/2015,debtconsolidation,0.0,18909.0,48 months,9.23,473,A1,...,2,13,10.0,4,15105,58.80,15,0,0,0
50071,1736121,2899966,10/18/2015,homeimprovement,0.0,32755.0,36 months,13.28,1108,E2,...,5,18,12.0,11,17368,52.77,0,0,0,0
10766,1011544,2899968,10/17/2014,auto,0.0,21339.0,60 months,15.24,510,B3,...,29,11,7.0,5,21821,80.80,0,0,0,7
30030,1755851,2899969,7/31/2014,debtconsolidation,0.0,21291.0,60 months,11.76,471,E3,...,6,14,12.0,6,12396,67.49,0,5,4,1
77769,1490924,2899987,6/4/2015,debtconsolidation,0.0,20052.0,36 months,16.27,708,C3,...,37,9,7.0,4,19878,38.54,13,0,0,1

In [5]:
merged_df.dtypes

loanId                        int64
memberId                      int64
date                         object
purpose                      object
isJointApplication          float64
loanAmount                  float64
term                         object
interestRate                float64
monthlyPayment                int64
grade                        object
loanStatus                   object
residentialState             object
yearsEmployment              object
homeOwnership                object
annualIncome                  int64
incomeVerified                int64
dtiRatio                    float64
lengthCreditHistory           int64
numTotalCreditLines           int64
numOpenCreditLines          float64
numOpenCreditLines1Year       int64
revolvingBalance              int64
revolvingUtilizationRate    float64
numDerogatoryRec              int64
numDelinquency2Years          int64
numChargeoff1year             int64
numInquiries6Mon              int64
dtype: object

In [7]:
merged_df.count()

loanId                      100000
memberId                    100000
date                        100000
purpose                     100000
isJointApplication           99029
loanAmount                   98994
term                         98929
interestRate                100000
monthlyPayment              100000
grade                       100000
loanStatus                  100000
residentialState            100000
yearsEmployment             100000
homeOwnership               100000
annualIncome                100000
incomeVerified              100000
dtiRatio                    100000
lengthCreditHistory         100000
numTotalCreditLines         100000
numOpenCreditLines           99033
numOpenCreditLines1Year     100000
revolvingBalance            100000
revolvingUtilizationRate    100000
numDerogatoryRec            100000
numDelinquency2Years        100000
numChargeoff1year           100000
numInquiries6Mon            100000
dtype: int64

In [6]:
mean_global = merged_df.mean()
mean_global[3]

20658.524587348729

In [7]:
null_columns = merged_df.columns[merged_df.isnull().any()].tolist()
null_columns

# merged_df[merged_df.isnull().loanAmount]

['isJointApplication', 'loanAmount', 'term', 'numOpenCreditLines']

In [8]:
mode_jointapp = merged_df.isJointApplication.mode()[0]
mean_loan = round(merged_df.loanAmount.mean())
mode_term = merged_df.term.mode()[0]
mean_numopen = round(merged_df.numOpenCreditLines.mean())

In [9]:
merged_df[["isJointApplication"]] = merged_df[["isJointApplication"]].fillna(value=mode_jointapp)
merged_df[["loanAmount"]] = merged_df[["loanAmount"]].fillna(value=mean_loan)
merged_df[["term"]] = merged_df[["term"]].fillna(value=mode_term)
merged_df[["numOpenCreditLines"]] = merged_df[["numOpenCreditLines"]].fillna(value=mean_numopen)

# merged_df[merged_df.isnull().term]

In [12]:
merged_df.to_csv('data/merged_cleaned.csv')
print("Data cleaned...")

Data cleaned...